name: Release
on:
  release:
    types: [published]

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.12
      - name: Install dependencies  
        run: pip3 install -r requirements.txt
      - name: Replace Version
        run: sed -i "s/0.1.0/$RELEASE_VERSION/g" pyproject.toml
      - name: Build
        run: python -m build --wheel
      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload dist/*
